import { join } from 'node:path';

import type { Page } from '@playwright/test';

import { expect, test, uniqueName } from '../support/fixtures';

/**
 * M6 end to end: reading a note format out of an uploaded file, editing one,
 * and giving it drafting instructions.
 *
 * The fixtures are the server's own extraction fixtures rather than copies.
 * They are generated by `server/src/extract/__fixtures__/make.mjs`, every word
 * in them is fabricated, and pointing at them here means the file the browser
 * uploads is the file the unit tests parse.
 */
const FIXTURES = join(import.meta.dirname, '..', '..', 'server', 'src', 'extract', '__fixtures__');

/** A two-column blank form: labels left, empty cells right. */
const TABLE_TEMPLATE = join(FIXTURES, 'template-table.docx');
/** A completed note, for the "2-3 example notes" path. */
const EXAMPLE_NOTE = join(FIXTURES, 'example-note.docx');
/** A scan: pages of pictures, no text layer. */
const SCAN = join(FIXTURES, 'scan.pdf');

const chipsOf = (page: Page) => page.getByTestId('section-chips');

/** Remove one expected line from the collected console errors, in place. */
function drop(collected: string[], line: string): void {
  const remaining = collected.filter((entry) => entry !== line);
  collected.splice(0, collected.length, ...remaining);
}

test.describe('reading a format out of an uploaded file', () => {
  test('takes a .docx template through the confirm screen and into a note', async ({ page }) => {
    const formatName = uniqueName('E2E uploaded intake');
    const patientName = uniqueName('E2E Upload Patient');

    await page.goto('/onboarding/format');
    await page.getByText('Upload a blank template').click();

    // Exactly what a real drop does — the dashed area and the picker write the
    // same state, so setting files on the input exercises the shipped path.
    await page.getByTestId('area-template-input').setInputFiles(TABLE_TEMPLATE);
    await expect(page.getByTestId('area-template-files')).toContainText('template-table.docx');

    await page.getByTestId('format-continue').click();
    await expect(page.getByRole('heading', { name: "Here's what we found" })).toBeVisible();

    // These four came out of the document. A template laid out as a table is
    // the shape that breaks a naive parser, so seeing its labels as chips is
    // the assertion that the file was actually read.
    const chips = chipsOf(page);
    await expect(chips).toContainText('Presenting problem');
    await expect(chips).toContainText('History');
    await expect(chips).toContainText('Formulation');
    await expect(chips).toContainText('Plan');

    // Rename and reorder before saving — up/down rather than drag.
    await chips.getByRole('button', { name: 'Rename History' }).click();
    await chips.getByLabel('New name for History').fill('Background');
    await chips.getByLabel('New name for History').press('Enter');
    await expect(chips).toContainText('Background');

    await chips.getByRole('button', { name: 'Move Plan up' }).click();
    await expect(chips.locator('.section-chip').nth(2)).toContainText('Plan');
    await expect(chips.locator('.section-chip').nth(3)).toContainText('Formulation');

    await page.getByLabel('Format name').fill(formatName);
    await page.getByTestId('save-format').click();

    // The prototype's flow: saving a format lands on adding a patient.
    await expect(page.getByRole('heading', { name: 'Add patient' })).toBeVisible();
    await page.getByLabel('Name').fill(patientName);
    await page.getByRole('button', { name: 'Add patient' }).click();

    // The whole point of the upload: the format is usable for a note.
    await page.getByRole('button', { name: 'New note' }).click();
    await page.getByLabel('Note format').selectOption({ label: formatName });
    await page.getByTestId('summary-input').fill('First session, new client, anxious about work.');
    await page.getByTestId('process-note').click();

    const body = page.getByTestId('note-body');
    await expect(body).toContainText('Presenting problem:');
    await expect(body).toContainText('Background:');
    // The order she set on the confirm screen is the order the note is in.
    await expect(body).toContainText(/Plan:[\s\S]*Formulation:/);
  });

  test('needs two example notes before it will read them', async ({ page }) => {
    await page.goto('/onboarding/format');
    await page.getByText('Upload a few example notes').click();

    await page.getByTestId('area-examples-input').setInputFiles([EXAMPLE_NOTE]);
    await expect(page.getByTestId('format-continue')).toBeDisabled();

    await page.getByTestId('area-examples-input').setInputFiles([EXAMPLE_NOTE, EXAMPLE_NOTE]);
    await expect(page.getByTestId('format-continue')).toBeEnabled();

    await page.getByTestId('format-continue').click();
    await expect(page.getByRole('heading', { name: "Here's what we found" })).toBeVisible();
    await expect(chipsOf(page)).toContainText('Subjective');
  });

  test('refuses a scan and offers the path that cannot fail', async ({ page, consoleErrors }) => {
    await page.goto('/onboarding/format');
    await page.getByText('Upload a blank template').click();
    await page.getByTestId('area-template-input').setInputFiles(SCAN);
    await page.getByTestId('format-continue').click();

    const alert = page.getByRole('alert');
    await expect(alert).toContainText('scan');
    await alert.getByRole('button', { name: 'Describe it myself' }).click();
    await expect(page.getByTestId('area-manual')).toBeVisible();

    // The 400 is the point of this test, and Chrome logs every failed request
    // to the console itself. Dropping exactly that line keeps the suite's
    // no-console-errors rule — which is about the app shouting, not about a
    // rejection the app asked for and handled — while leaving anything else
    // the page logged to fail the run.
    drop(consoleErrors, 'Failed to load resource: the server responded with a status of 400 (Bad Request)');
  });
});

test.describe('editing a format from Settings', () => {
  test('renames a section and saves drafting instructions', async ({ page }) => {
    const formatName = uniqueName('E2E editable note');

    // Create it through the Settings entry point, so saving returns there.
    await page.goto('/settings');
    await page.getByRole('link', { name: 'Add another format' }).click();
    await page.getByText('Describe it myself').click();
    await page.getByLabel('Format name').fill(formatName);
    await page.getByLabel('Sections').fill('Subjective, Objective, Assessment, Plan');
    await page.getByTestId('format-continue').click();
    await page.getByTestId('save-format').click();

    const row = page.getByTestId('format-list').locator('.patient-row').filter({ hasText: formatName });
    await expect(row).toBeVisible();
    await row.getByRole('link', { name: 'Edit' }).click();

    await expect(page.getByRole('heading', { name: 'Edit note format' })).toBeVisible();
    // The packet's rule, said out loud on the screen she is editing.
    await expect(page.getByText(/keep the sections they were written with/)).toBeVisible();

    const chips = chipsOf(page);
    await chips.getByRole('button', { name: 'Rename Objective' }).click();
    await chips.getByLabel('New name for Objective').fill('Observations');
    await chips.getByLabel('New name for Objective').press('Enter');

    const instructions = 'Use "client", not "patient". Keep her hedging exactly as she voiced it.';
    await page.getByLabel('Instructions').fill(instructions);
    await expect(page.getByTestId('instructions-budget')).toContainText('tokens');
    await page.getByTestId('save-format').click();

    // Back on Settings, and both changes survived a round trip to the server.
    await expect(row).toContainText('Observations');
    await row.getByRole('link', { name: 'Edit' }).click();
    await expect(page.getByLabel('Instructions')).toHaveValue(instructions);
  });

  test('imports a skill file into the instructions and warns about its references', async ({ page }) => {
    const formatName = uniqueName('E2E skill note');

    await page.goto('/settings');
    await page.getByRole('link', { name: 'Add another format' }).click();
    await page.getByText('Describe it myself').click();
    await page.getByLabel('Format name').fill(formatName);
    await page.getByLabel('Sections').fill('Subjective, Plan');
    await page.getByTestId('format-continue').click();
    await page.getByTestId('save-format').click();

    await page
      .getByTestId('format-list')
      .locator('.patient-row')
      .filter({ hasText: formatName })
      .getByRole('link', { name: 'Edit' })
      .click();

    await page
      .getByTestId('skill-file-input')
      .setInputFiles(
        join(import.meta.dirname, '..', '..', 'server', 'src', 'skill', '__fixtures__', 'skill', 'SKILL.md'),
      );

    // The frontmatter is gone, the instruction body is not, and the panel says
    // what it did rather than rewriting silently.
    const textarea = page.getByLabel('Instructions');
    await expect(textarea).toHaveValue(/Willow Creek progress note/);
    await expect(textarea).not.toHaveValue(/allowed-tools/);
    await expect(page.getByTestId('import-report')).toContainText('frontmatter removed');

    // It warns rather than inlining: choosing what part of a reference file is
    // the needed content is judgement, and a wrong inline blows the budget.
    await expect(page.getByTestId('import-references')).toContainText('references/FORMS.md');
  });
});
