#!/usr/bin/env node
/**
 * Record → transcript → draft, timed, against a disposable Apunta instance.
 *
 * The browser capture itself is not in this path: it posts a real synthetic
 * WAV (Piper speech, generated by `scripts/synthetic-acceptance/
 * generate-audio.mjs`) to `POST /api/transcribe`, which is the same request the
 * capture screen makes. The SSE stream is timestamped per event so the phases
 * separate: `progress` events are whisper, the first `status`/`token` is the
 * model load plus prefill, and `note` is the draft's end.
 *
 *   node tools/model-lab/e2e-timing.mjs --base http://127.0.0.1:7720 \
 *     --wav /tmp/apunta-synthetic-dictation-padded.wav --runs 3 --out /tmp/fl-lab/e2e.json
 */
import { readFileSync, writeFileSync } from 'node:fs';

function parseArgs(argv) {
  const args = { base: 'http://127.0.0.1:7720', wav: '', runs: 3, out: undefined, label: '' };
  for (let i = 0; i < argv.length; i += 1) {
    const flag = argv[i];
    const value = argv[i + 1];
    switch (flag) {
      case '--base':
        args.base = String(value);
        i += 1;
        break;
      case '--wav':
        args.wav = String(value);
        i += 1;
        break;
      case '--runs':
        args.runs = Number(value);
        i += 1;
        break;
      case '--out':
        args.out = String(value);
        i += 1;
        break;
      case '--label':
        args.label = String(value);
        i += 1;
        break;
      default:
        if (flag?.startsWith('--')) throw new Error(`unknown flag ${flag}`);
    }
  }
  return args;
}

async function pick(base) {
  const patients = await (await fetch(`${base}/api/patients`)).json();
  const formats = await (await fetch(`${base}/api/formats`)).json();
  const list = patients.patients ?? patients;
  const formatList = formats.formats ?? formats;
  if (!Array.isArray(list) || list.length === 0) throw new Error('no patients in the disposable instance');
  if (!Array.isArray(formatList) || formatList.length === 0) throw new Error('no formats');
  return { patientId: list[0].id, formatId: formatList[0].id };
}

/** One transcribe call, with every SSE event timestamped from the request. */
async function oneRun(args, ids, wav, run) {
  const form = new FormData();
  form.set('patient_id', ids.patientId);
  form.set('format_id', ids.formatId);
  form.set('title', `Synthetic end-to-end ${String(run)}`);
  form.set('audio', new Blob([wav], { type: 'audio/wav' }), 'dictation.wav');

  const began = Date.now();
  const response = await fetch(`${args.base}/api/transcribe`, { method: 'POST', body: form });
  if (!response.body) throw new Error('no stream');
  const reader = response.body.getReader();
  const decoder = new TextDecoder();
  let buffer = '';
  const events = [];
  let transcript = '';
  let note = null;
  let failure = null;
  for (;;) {
    const { done, value } = await reader.read();
    if (done) break;
    buffer += decoder.decode(value, { stream: true });
    let newline = buffer.indexOf('\n');
    while (newline !== -1) {
      const line = buffer.slice(0, newline).trim();
      buffer = buffer.slice(newline + 1);
      newline = buffer.indexOf('\n');
      if (!line.startsWith('data:')) continue;
      const payload = JSON.parse(line.slice(5).trim());
      const at = Date.now() - began;
      events.push({ name: payload.event, at, data: payload.data });
      if (payload.event === 'status' && payload.data?.stage === 'transcribing') transcript = '';
      if (payload.event === 'error') failure = payload.data?.message ?? 'error';
      if (payload.event === 'note') note = payload.data?.note ?? null;
    }
  }
  const total = Date.now() - began;
  const progress = events.filter((event) => event.name === 'progress');
  const firstStatus = events.find((event) => event.name === 'status' && event.data?.stage !== 'transcribing');
  const firstToken = events.find((event) => event.name === 'token');
  const done = events.find((event) => event.name === 'note' || event.name === 'error');
  return {
    run,
    totalMs: total,
    whisperMs: firstStatus ? firstStatus.at : null,
    draftFirstStatusMs: firstStatus ? firstStatus.at : null,
    draftFirstTokenMs: firstToken ? firstToken.at : null,
    draftEndMs: done ? done.at : null,
    draftMs: firstStatus && done ? done.at - firstStatus.at : null,
    progressEvents: progress.length,
    transcriptChars: transcript.length,
    noteSections: note ? Object.keys(note.sections ?? {}).length : 0,
    failure,
  };
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const wav = readFileSync(args.wav);
  const ids = await pick(args.base);
  const runs = [];
  for (let run = 1; run <= args.runs; run += 1) {
    const result = await oneRun(args, ids, wav, run);
    runs.push(result);
    process.stderr.write(`  run ${String(run)}: total ${String(result.totalMs)} ms\n`);
  }
  const summary = { label: args.label, base: args.base, wav: args.wav, bytes: wav.length, patientId: ids.patientId, formatId: ids.formatId, runs };
  process.stdout.write(`${JSON.stringify(summary, null, 2)}\n`);
  if (args.out !== undefined) writeFileSync(args.out, `${JSON.stringify(summary, null, 2)}\n`, 'utf8');
}

await main();
