/**
 * Regenerate the binary extraction fixtures.
 *
 *     node server/src/extract/__fixtures__/make.mjs
 *
 * The `.docx` and `.pdf` files next to this script are real binaries — a unit
 * test for a document extractor cannot fake them — so they are generated by a
 * script that is itself reviewable rather than checked in as opaque blobs.
 * Both the script and its output are committed, so the tests never depend on
 * running it.
 *
 * **Every word of clinical content here is fabricated** (CLAUDE.md hard rule
 * 2): John Smith from the prototype's sample practice, at a clinic that does
 * not exist.
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { strToU8, zipSync } from 'fflate';

const here = dirname(fileURLToPath(import.meta.url));
const out = (name) => join(here, name);

// --- .docx ---------------------------------------------------------------

const CONTENT_TYPES = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
<Default Extension="xml" ContentType="application/xml"/>
<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
<Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/>
</Types>`;

const ROOT_RELS = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
</Relationships>`;

/** Heading 1/2 plus one workplace style whose name says nothing to a parser. */
const STYLES = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
<w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="heading 1"/></w:style>
<w:style w:type="paragraph" w:styleId="Heading2"><w:name w:val="heading 2"/></w:style>
<w:style w:type="paragraph" w:styleId="SectionHead"><w:name w:val="Section Head"/></w:style>
</w:styles>`;

const esc = (text) => text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

/** A `w:p` with an optional paragraph style and optional direct bold. */
function para(text, { style = null, bold = false } = {}) {
  const pPr = style === null ? '' : `<w:pPr><w:pStyle w:val="${style}"/></w:pPr>`;
  if (text === '') return `<w:p>${pPr}</w:p>`;
  const rPr = bold ? '<w:rPr><w:b/></w:rPr>' : '';
  return `<w:p>${pPr}<w:r>${rPr}<w:t xml:space="preserve">${esc(text)}</w:t></w:r></w:p>`;
}

/** A two-column row: a label on the left, an empty cell on the right. */
function labelRow(label) {
  const cell = (inner) => `<w:tc><w:tcPr/>${inner}</w:tc>`;
  return `<w:tr>${cell(para(label, { bold: true }))}${cell(para(''))}</w:tr>`;
}

function document(bodyXml) {
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
<w:body>${bodyXml}<w:sectPr/></w:body>
</w:document>`;
}

function docx(name, bodyXml) {
  const zipped = zipSync(
    {
      '[Content_Types].xml': strToU8(CONTENT_TYPES),
      '_rels/.rels': strToU8(ROOT_RELS),
      'word/document.xml': strToU8(document(bodyXml)),
      'word/styles.xml': strToU8(STYLES),
    },
    // A fixed mtime keeps the bytes stable across regenerations, so a rerun of
    // this script does not show up as a diff when nothing actually changed.
    { mtime: new Date('2026-01-01T00:00:00Z'), level: 6 },
  );
  writeFileSync(out(name), zipped);
}

/** (a) headings carried by paragraph styles, which raw text erases. */
docx(
  'template-headings.docx',
  [
    para('Willow Creek Counseling — Progress Note', { style: 'Heading1' }),
    para('Subjective', { style: 'Heading2' }),
    para(''),
    para('Objective', { style: 'Heading2' }),
    para(''),
    para('Assessment', { style: 'Heading2' }),
    para(''),
    para('Plan', { style: 'Heading2' }),
    para(''),
  ].join(''),
);

/** (b) a two-column table: label left, blank right. */
docx(
  'template-table.docx',
  [
    para('Willow Creek Counseling — Intake', { style: 'SectionHead' }),
    `<w:tbl><w:tblPr/>${[
      labelRow('Presenting problem'),
      labelRow('History'),
      labelRow('Formulation'),
      labelRow('Plan'),
    ].join('')}</w:tbl>`,
  ].join(''),
);

/** (c) a completed note — the `examples` path. Fabricated throughout. */
docx(
  'example-note.docx',
  [
    para('Subjective', { bold: true }),
    para(
      'John Smith reports improved sleep since the last session and fewer intrusive thoughts during the workday.',
    ),
    para('Objective', { bold: true }),
    para('Alert and engaged. The restlessness noted at earlier sessions was not present.'),
    para('Assessment', { bold: true }),
    para('Continued progress on anxiety management goals.'),
    para('Plan', { bold: true }),
    para('Continue weekly sessions. Introduce grounding exercises for use between sessions.'),
  ].join(''),
);

// --- .pdf ----------------------------------------------------------------

/**
 * A minimal one-page PDF, written by hand so the bytes are auditable.
 * `lines` is `[text, fontSize, y]`; an empty `lines` gives the scan case — a
 * page with a drawn rectangle and no text at all.
 */
function pdf(name, lines) {
  const content =
    lines.length === 0
      ? '72 600 300 120 re S\n'
      : lines
          .map(
            ([text, size, y]) =>
              `BT /F1 ${size} Tf 72 ${y} Td (${text.replace(/([()\\])/g, '\\$1')}) Tj ET\n`,
          )
          .join('');

  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] ' +
      '/Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>',
    `<< /Length ${content.length} >>\nstream\n${content}endstream`,
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>',
  ];

  let body = '%PDF-1.4\n';
  const offsets = [];
  objects.forEach((object, index) => {
    offsets.push(body.length);
    body += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });

  const xrefAt = body.length;
  let xref = `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const offset of offsets) xref += `${String(offset).padStart(10, '0')} 00000 n \n`;

  const trailer = `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefAt}\n%%EOF\n`;
  writeFileSync(out(name), Buffer.from(body + xref + trailer, 'latin1'));
}

/** A blank template printed to PDF: bigger headings, nothing under them. */
pdf('template.pdf', [
  ['Willow Creek Counseling - Progress Note', 16, 720],
  ['Subjective', 13, 680],
  ['Objective', 13, 620],
  ['Assessment', 13, 560],
  ['Plan', 13, 500],
]);

/** The dangerous case: a scan. Pages of pictures, no text layer. */
pdf('scan.pdf', []);

// --- the rejected types --------------------------------------------------

/** A 1x1 PNG. People upload screenshots of a template; this must fail politely. */
writeFileSync(
  out('screenshot.png'),
  Buffer.from(
    'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==',
    'base64',
  ),
);

/** TextEdit's default. Sniffed by its magic bytes, rejected with a Save-As hint. */
writeFileSync(
  out('template.rtf'),
  '{\\rtf1\\ansi\\deff0 {\\fonttbl{\\f0 Helvetica;}}\\f0\\fs24 Subjective\\par Objective\\par}\n',
  'latin1',
);

console.log('fixtures written to', here);
